In [15]:
import tensorflow as tf
import numpy as np

In [56]:
with open("data.txt") as data:
    for line in data:
        token = tf.contrib.keras.preprocessing.text.Tokenizer(num_words=4)
        print tf.contrib.keras.preprocessing.text.Tokenizer.fit_on_texts(token,line)

None


In [57]:
        print tf.contrib.keras.preprocessing.text.Tokenizer.texts_to_matrix(token,line)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 ..., 
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [58]:
        print tf.contrib.keras.preprocessing.text.text_to_word_sequence(line)

['if', 'you', 'have', 'ever', 'dreamt', 'of', 'spending', 'a', 'night', 'on', 'a', 'kettuvallum', 'rice', 'barge', 'houseboat', 'cruising', 'the', 'backwaters', 'while', 'an', 'on', 'board', 'chef', 'prepares', 'fresh', 'barbecued', 'fish', 'or', 'a', 'succulent', 'keralan', 'curry', 'you\xe2\x80\x99ve', 'already', 'got', 'the', 'kerala', 'bug', 'but', 'there\xe2\x80\x99s', 'a', 'whole', 'other', 'kerala', 'lying', 'north', 'of', 'kochi', 'that', 'is', 'only', 'just', 'starting', 'to', 'capture', 'travellers\xe2\x80\x99', 'imaginations', 'the', 'beaches', 'backwaters', 'and', 'wildlife', 'sanctuaries', 'in', 'the', 'southern', 'half', 'of', 'the', 'state', 'are', 'now', 'established', 'stops', 'on', 'the', 'traveller', 'trail', 'but', 'those', 'in', 'the', 'know', 'are', 'turning', 'their', 'attention', 'to', 'the', 'north', 'of', 'kerala', 'where', 'the', 'arabian', 'sea', 'beaches', 'are', 'just', 'as', 'gobsmacking', 'the', 'wildlife', 'sanctuaries', 'just', 'as', 'teeming', 'the', 

In [59]:
        print tf.contrib.keras.preprocessing.text.Tokenizer.texts_to_sequences_generator(token,line)

<generator object texts_to_sequences_generator at 0x7fb2f52a0e10>
